'use client';
import{useEffect,useState}from'react';import{orderRepository}from'@/lib/data/repositories/order-repository';import{courseRepository}from'@/lib/data/repositories/course-repository';import type{Course}from'@/types/course';
export default function Orders(){const[o,setO]=useState<any[]>([]);const[courses,setCourses]=useState<Course[]>([]);const[search,setSearch]=useState('');const[open,setOpen]=useState(false);const[form,setForm]=useState({name:'',email:'',phone:'',courseId:'',price:''});
 async function load(){const[a,b]=await Promise.all([orderRepository.findAll(),courseRepository.findAll()]);setO(a);setCourses(b)}useEffect(()=>{void load()},[]);
 async function approve(id:string){await orderRepository.confirmOrder(id);await load()}async function cancel(id:string){await orderRepository.cancelOrder(id);await load()}async function remove(id:string){if(!confirm('هل تريد حذف الطلب نهائيًا؟'))return;await orderRepository.delete(id);await load()}
 async function add(e:React.FormEvent){e.preventDefault();const course=courses.find(x=>x.id===form.courseId);if(!course)return alert('اختر المنتج.');const amount=Number(form.price||course.price||0);await orderRepository.create({customer:{traineeId:'',name:form.name,email:form.email,phone:form.phone},items:[{id:`item-${Date.now()}`,type:course.type==='training'?'training-program':'course',itemId:course.id,title:course.title,quantity:1,unitPrice:amount,totalPrice:amount}],subtotal:amount,discount:0,tax:0,total:amount,currency:'SAR',payment:{method:'bank-transfer',status:'pending',amount,currency:'SAR'},status:'pending',notes:'تمت إضافة الطلب يدويًا من لوحة التحكم'});setOpen(false);setForm({name:'',email:'',phone:'',courseId:'',price:''});await load()}
 const visible=o.filter(x=>!search||`${x.orderNumber} ${x.customer?.name} ${x.customer?.email}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="admin-page" dir="rtl"><header className="admin-page-header"><div><div className="eyebrow">Admin</div><h1>الطلبات</h1><p>متابعة الطلبات وحالات الدفع والتنفيذ.</p></div><div className="admin-actions"><button className="admin-btn admin-btn-primary" onClick={()=>setOpen(true)}>+ إضافة طلب</button><button className="admin-btn admin-btn-light" onClick={()=>window.print()}>طباعة</button></div></header><div className="admin-toolbar"><input className="admin-input" placeholder="البحث في الطلبات..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="admin-table-card"><table className="admin-table"><thead><tr><th>رقم الطلب</th><th>العميل</th><th>المنتج</th><th>الإجمالي</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>{visible.map(x=><tr key={x.id}><td>{x.orderNumber}</td><td><strong>{x.customer?.name}</strong><br/><small>{x.customer?.email}</small></td><td>{x.items?.[0]?.title||'—'}</td><td>{Number(x.total||0).toLocaleString('ar-SA')} SAR</td><td>{x.status}</td><td><button className="admin-btn admin-btn-light" onClick={()=>void approve(x.id)}>اعتماد</button>{' '}<button className="admin-btn admin-btn-danger" onClick={()=>void cancel(x.id)}>إلغاء</button>{' '}<button className="admin-btn admin-btn-danger" onClick={()=>void remove(x.id)}>حذف</button></td></tr>)}</tbody></table></div>
 {open&&<div className="admin-modal-backdrop"><form className="admin-modal" style={{maxWidth:650}} onSubmit={add}><div className="admin-modal-header"><h2>إضافة طلب</h2><button type="button" className="admin-modal-close" onClick={()=>setOpen(false)}>×</button></div><div className="admin-modal-body"><div className="admin-form-grid"><div className="admin-field"><label>اسم العميل</label><input className="admin-input" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="admin-field"><label>البريد الإلكتروني</label><input className="admin-input" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="admin-field"><label>رقم الجوال</label><input className="admin-input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="admin-field"><label>المنتج</label><select className="admin-select" required value={form.courseId} onChange={e=>{const x=courses.find(c=>c.id===e.target.value);setForm({...form,courseId:e.target.value,price:String(x?.price??'')})}}><option value="">اختر المنتج</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></div><div className="admin-field"><label>السعر</label><input className="admin-input" type="number" min="0" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></div></div></div><div className="admin-modal-footer"><button type="button" className="admin-btn admin-btn-light" onClick={()=>setOpen(false)}>إلغاء</button><button className="admin-btn admin-btn-primary">حفظ الطلب</button></div></form></div>}</main>}
